[package]
name = "ensure-no_std"
version = "0.1.0"
edition = "2021"


[dependencies]
lambdaworks-math = { path = "../math", default-features = false }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
