[package]
name = "no_gpu_fuzz"
version.workspace = true
edition.workspace = true

[package.metadata]
cargo-fuzz = true

[dependencies]
lambdaworks-math = { workspace = true }
lambdaworks-gpu = { workspace = true }
libfuzzer-sys = { workspace = true }
stark-platinum-prover = { workspace = true }

num-traits = "0.2"
ibig = "0.3.6"

[[bin]]
name = "field_fuzzer"
path = "fuzz_targets/field_fuzzer.rs"
test = false
doc = false

[[bin]]
name = "field_from_hex"
path = "fuzz_targets/field_from_hex.rs"
test = false
doc = false

[[bin]]
name = "field_from_raw"
path = "fuzz_targets/field_from_raw.rs"
test = false
doc = false

[[bin]]
name = "deserialize_stark_proof"
path = "fuzz_targets/deserialize_stark_proof.rs"
test = false
doc = false


