[package]
name = "metal_fuzz"
version.workspace = true
edition.workspace = true

[package.metadata]
cargo-fuzz = true

[dependencies]
lambdaworks-math = { workspace = true, features = ["metal"] }
lambdaworks-gpu = { workspace = true, features = ["metal"] }
libfuzzer-sys = { workspace = true }

[[bin]]
name = "fft_diff"
path = "fuzz_targets/fft_diff.rs"
test = false
doc = false

[[bin]]
name = "polynomial_fft_diff"
path = "fuzz_targets/polynomial_fft_diff.rs"
test = false
doc = false

[[bin]]
name = "twiddles_generation_diff"
path = "fuzz_targets/twiddles_generation_diff.rs"
test = false
doc = false

