name: Deploy Miden Assembly Playground

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install WASM
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "latest"

      - name: Install and Build 🔧
        run: |
          cd playground
          npm run build:miden
          npm install
          npm run build
          npx webpack
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playground/build/
